#!/usr/bin/env python3
"""
Fix knowledge templates by regenerating clean knowledge entries
"""

import json
import os

# Template patterns to remove
TEMPLATE_PATTERNS = [
    "Your question about",
    "Thank you for asking about", 
    "Regarding your inquiry about",
    "Practically, this allows better understand and interact with our world",
    "Important features are its fundamental properties and real-world impacts",
    "This enables us to better understand and interact with our world",
    "Core components involve its fundamental properties and real-world impacts",
    "Notable characteristics are its fundamental properties and real-world impacts",
    "Key aspects include its fundamental properties and real-world impacts",
    "This is essential for better understand and interact with our world",
    "In everyday life, this helps us better understand and interact with our world",
    "It encompasses multiple aspects and applications across various fields of study"
]

# Better content for astronomy topics
CLEAN_CONTENT = {
    "sun": "The Sun is a G-type main-sequence star at the center of our solar system. It generates energy through nuclear fusion, converting hydrogen into helium at its core. With a surface temperature of about 5,778 K (5,505°C), it provides the light and heat essential for life on Earth.",
    "moon": "The Moon is Earth's only natural satellite, formed about 4.5 billion years ago. It orbits Earth at an average distance of 384,400 km and is responsible for ocean tides through its gravitational pull. The Moon has phases due to its changing position relative to Earth and the Sun.",
    "earth": "Earth is the third planet from the Sun and the only known planet to harbor life. With a diameter of about 12,742 km, it has a diverse climate system, liquid water oceans covering 71% of its surface, and a protective magnetic field generated by its iron core.",
    "mars": "Mars is the fourth planet from the Sun, often called the Red Planet due to iron oxide on its surface. It has the largest volcano in the solar system (Olympus Mons), polar ice caps, and evidence of ancient river valleys, suggesting it once had liquid water.",
    "space": "Space is the vast expanse beyond Earth's atmosphere, characterized by a near-perfect vacuum with extremely low density of particles. It begins at the Kármán line (100 km above sea level) and extends infinitely, containing all celestial bodies, dark matter, and dark energy.",
    "astronomy": "Astronomy is the scientific study of celestial objects, space, and the universe as a whole. It combines physics, chemistry, and mathematics to understand phenomena ranging from planets and stars to galaxies and cosmic evolution. Modern astronomy uses telescopes across the electromagnetic spectrum.",
    "universe": "The universe encompasses all of space, time, matter, and energy. It began approximately 13.8 billion years ago with the Big Bang and has been expanding ever since. It contains billions of galaxies, each with billions of stars, along with dark matter and dark energy.",
    "galaxy": "A galaxy is a massive collection of stars, gas, dust, and dark matter bound together by gravity. Our Milky Way galaxy contains 200-400 billion stars and is about 100,000 light-years in diameter. Galaxies come in spiral, elliptical, and irregular shapes.",
    "planet": "A planet is a celestial body that orbits a star, has sufficient mass for a nearly round shape, and has cleared its orbital path. Our solar system has eight planets: four rocky inner planets and four gas/ice giants in the outer system.",
    "star": "A star is a massive sphere of plasma held together by gravity, generating light and heat through nuclear fusion. Stars form from collapsing gas clouds and vary widely in size, temperature, and lifespan, from red dwarfs that last trillions of years to blue giants that burn out in millions."
}

def clean_content(content):
    """Remove template patterns from content"""
    cleaned = content
    for pattern in TEMPLATE_PATTERNS:
        cleaned = cleaned.replace(pattern, "")
    
    # Clean up extra spaces and periods
    cleaned = " ".join(cleaned.split())
    cleaned = cleaned.replace(". .", ".")
    cleaned = cleaned.replace("  ", " ")
    
    return cleaned.strip()

def fix_knowledge_file(filepath):
    """Fix a single knowledge file"""
    print(f"Processing {filepath}...")
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    if 'entries' not in data:
        print(f"  Skipping {filepath} - no entries found")
        return
    
    fixed_count = 0
    for entry in data['entries']:
        topic = entry.get('topic', '').lower()
        
        # Check if we have clean content for this topic
        if topic in CLEAN_CONTENT:
            old_content = entry['content']
            entry['content'] = CLEAN_CONTENT[topic]
            
            # Update conversational patterns
            if 'metadata' in entry and 'conversational_patterns' in entry['metadata']:
                patterns = [
                    CLEAN_CONTENT[topic],
                    CLEAN_CONTENT[topic],
                    f"To explain {topic}: {CLEAN_CONTENT[topic]}",
                    f"Let me tell you about {topic}. {CLEAN_CONTENT[topic]}",
                    f"{topic.capitalize()} - {CLEAN_CONTENT[topic]}",
                    f"When describing {topic}, {CLEAN_CONTENT[topic].lower()}"
                ]
                entry['metadata']['conversational_patterns'] = patterns
            
            fixed_count += 1
            print(f"  Fixed: {topic}")
        else:
            # For other topics, just clean the templates
            old_content = entry['content']
            cleaned = clean_content(old_content)
            
            if cleaned != old_content:
                entry['content'] = cleaned
                
                # Update conversational patterns
                if 'metadata' in entry and 'conversational_patterns' in entry['metadata']:
                    entry['metadata']['conversational_patterns'] = [
                        clean_content(p) for p in entry['metadata']['conversational_patterns']
                    ]
                
                fixed_count += 1
                print(f"  Cleaned: {entry.get('topic', 'unknown')}")
    
    # Save the fixed file
    if fixed_count > 0:
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)
        print(f"  Updated {fixed_count} entries in {filepath}")
    else:
        print(f"  No changes needed for {filepath}")

def main():
    """Fix all knowledge files"""
    knowledge_dir = "/home/champi/Dev/think_ai/knowledge_files"
    
    print("Fixing knowledge template issues...")
    print("=" * 50)
    
    # Process all JSON files
    for filename in os.listdir(knowledge_dir):
        if filename.endswith('.json') and filename != 'enhanced_knowledge_index.json':
            filepath = os.path.join(knowledge_dir, filename)
            fix_knowledge_file(filepath)
    
    print("\n✅ Knowledge files fixed!")

if __name__ == "__main__":
    main()