[global]
cache-dir = ~/.think-ai-cache/pip
timeout = 60
retries = 2
trusted-host = pypi.org
               files.pythonhosted.org

[install]
find-links = file://~/.think-ai-cache/pip/wheels
no-cache-dir = false
prefer-binary = true

[wheel]
wheel-dir = ~/.think-ai-cache/pip/wheels