#!/bin/bash

echo "🚀 Think AI Coding CLI is ready!"
echo "================================"
echo ""
echo "✨ NEW: Mode switching! Use 'mode' to toggle between:"
echo "   - CODE mode: Generate actual code"
echo "   - CHAT mode: Answer questions & have conversations"
echo ""
echo "Quick examples to try:"
echo ""
echo "1. Start interactive coding session:"
echo "   ./target/release/think-ai-coding chat"
echo ""
echo "2. Generate Python code:"
echo "   ./target/release/think-ai-coding generate \"REST API with Flask\" --language python"
echo ""
echo "3. Generate JavaScript code:"
echo "   ./target/release/think-ai-coding generate \"React component with hooks\" --language javascript"
echo ""
echo "4. Generate Rust code:"
echo "   ./target/release/think-ai-coding generate \"web server with Axum\" --language rust"
echo ""
echo "5. Explain a concept:"
echo "   ./target/release/think-ai-coding explain \"hash tables\""
echo ""
echo "Starting interactive mode now..."
echo ""
exec ./target/release/think-ai-coding chat