#!/usr/bin/env python3
"""
Hugging Face Token Setup Script
Sets up HF token securely for the Think AI project
"""

import json
import os
import sys
from pathlib import Path


class HuggingFaceSetup:
    """O(1) Hugging Face token configuration"""

    def __init__(self):
        self.project_root = Path(__file__).parent
        self.env_file = self.project_root / ".env"
        self.token_cache = {}  # O(1) lookup cache

    def setup_token(self, token: str) -> bool:
        """Configure HF token with O(1) operations"""
        # Validate token format
        if not token or not token.startswith("hf_"):
            print("❌ Invalid token format")
            return False

        # Store in multiple locations for compatibility
        success = all(
            [
                self._update_env_file(token),
                self._update_bash_profile(token),
                self._update_gitignore(),
                self._create_huggingface_config(token),
            ]
        )

        if success:
            print("✅ Hugging Face token configured successfully")
            print(f"📁 Updated: {self.env_file}")
            print("🔒 Token excluded from git tracking")
            return True
        return False

    def _update_env_file(self, token: str) -> bool:
        """Update .env file with O(1) dict operations"""
        env_vars = {}

        # Read existing if present
        if self.env_file.exists():
            with open(self.env_file, "r") as f:
                for line in f:
                    if "=" in line and not line.strip().startswith("#"):
                        key, value = line.strip().split("=", 1)
                        env_vars[key] = value

        # Update token
        env_vars["HUGGINGFACE_TOKEN"] = token
        env_vars["HF_TOKEN"] = token
        env_vars["HUGGING_FACE_HUB_TOKEN"] = token

        # Write back
        with open(self.env_file, "w") as f:
            f.write("# Think AI Environment Variables\n")
            f.write("# Auto-generated by setup_huggingface.py\n\n")
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")

        # Set permissions
        os.chmod(self.env_file, 0o600)
        return True

    def _update_bash_profile(self, token: str) -> bool:
        """Add to shell profile for persistence"""
        home = Path.home()
        profiles = [home / ".bashrc", home / ".bash_profile", home / ".zshrc"]

        export_lines = [
            "\n# Hugging Face Token (Think AI)",
            f'export HUGGINGFACE_TOKEN="{token}"',
            f'export HF_TOKEN="{token}"',
            f'export HUGGING_FACE_HUB_TOKEN="{token}"\n',
        ]

        for profile in profiles:
            if profile.exists():
                content = profile.read_text()
                # Check if already present
                if "HUGGINGFACE_TOKEN" not in content:
                    with open(profile, "a") as f:
                        f.write("\n".join(export_lines))

        return True

    def _update_gitignore(self) -> bool:
        """Ensure token files are gitignored"""
        gitignore = self.project_root / ".gitignore"
        entries = {".env", ".env.local", ".env.*", "*.key", "*.token", ".huggingface/", "__pycache__/", "*.pyc"}

        existing = set()
        if gitignore.exists():
            existing = set(line.strip() for line in gitignore.read_text().splitlines())

        # Add missing entries
        to_add = entries - existing
        if to_add:
            with open(gitignore, "a") as f:
                f.write("\n# Security - Token Protection\n")
                for entry in sorted(to_add):
                    f.write(f"{entry}\n")

        return True

    def _create_huggingface_config(self, token: str) -> bool:
        """Create HF config for transformers library"""
        hf_dir = Path.home() / ".huggingface"
        hf_dir.mkdir(exist_ok=True)

        # Create token file
        token_file = hf_dir / "token"
        token_file.write_text(token)
        os.chmod(token_file, 0o600)

        # Create config
        config = {"token": token, "git_credential_helper_store": True}

        config_file = hf_dir / "config.json"
        with open(config_file, "w") as f:
            json.dump(config, f, indent=2)

        return True

    def verify_setup(self) -> bool:
        """Verify token is properly configured"""
        print("\n🔍 Verifying Hugging Face setup...")

        # Check environment variables
        checks = {
            "HUGGINGFACE_TOKEN": os.getenv("HUGGINGFACE_TOKEN"),
            "HF_TOKEN": os.getenv("HF_TOKEN"),
            "HUGGING_FACE_HUB_TOKEN": os.getenv("HUGGING_FACE_HUB_TOKEN"),
        }

        all_good = True
        for var, value in checks.items():
            if value and value.startswith("hf_"):
                print(f"✅ {var} is set")
            else:
                print(f"❌ {var} not found")
                all_good = False

        # Try importing transformers
        try:
            import transformers  # noqa: F401

            print("✅ Transformers library available")
        except ImportError:
            print("⚠️  Transformers not installed (pip install transformers)")

        return all_good


def main():
    """Main setup function"""
    token = os.getenv("HF_TOKEN", "")

    print("🤗 Hugging Face Token Setup for Think AI")
    print("=" * 50)

    setup = HuggingFaceSetup()

    if setup.setup_token(token):
        # Export to current shell
        os.environ["HUGGINGFACE_TOKEN"] = token
        os.environ["HF_TOKEN"] = token
        os.environ["HUGGING_FACE_HUB_TOKEN"] = token

        setup.verify_setup()

        print("\n📌 Next steps:")
        print("1. Restart your terminal or run: source ~/.bashrc")
        print("2. Test with: python -c 'import os; print(os.getenv(\"HF_TOKEN\"))'")
        print("3. Use in code: from transformers import AutoModel")

        return 0
    else:
        print("❌ Setup failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
