#!/bin/bash

# SSH Tunnel Setup for Local Access to Think AI Test Server
# This script helps you access the cloud GPU server from your local machine

echo "🌐 Think AI Local Access Setup"
echo "=============================="
echo ""
echo "Choose your preferred method to access the test server from your local machine:"
echo ""
echo "1️⃣  SSH Port Forwarding (Recommended for development)"
echo "   Run this command on YOUR LOCAL MACHINE:"
echo ""
echo "   ssh -L 9090:localhost:9090 administrator@<YOUR-GPU-SERVER-IP>"
echo ""
echo "   Then access: http://localhost:9090"
echo ""
echo "2️⃣  Using ngrok (For HTTPS and public URL)"
echo "   Run these commands on the GPU SERVER:"
echo ""
echo "   # Install ngrok if not already installed"
echo "   wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
echo "   tar -xzf ngrok-v3-stable-linux-amd64.tgz"
echo "   sudo mv ngrok /usr/local/bin/"
echo ""
echo "   # Start ngrok (you'll need to sign up for a free account at ngrok.com)"
echo "   ngrok http 9090"
echo ""
echo "3️⃣  Using SSH with specific bind address"
echo "   If you need to bind to all interfaces (less secure):"
echo ""
echo "   # Modify the test script to bind to 0.0.0.0 instead of 127.0.0.1"
echo "   # Then use SSH tunnel or access directly via GPU server IP"
echo ""
echo "4️⃣  Using Visual Studio Code Remote SSH"
echo "   - Install 'Remote - SSH' extension in VS Code"
echo "   - Connect to your GPU server"
echo "   - Port forwarding will be automatic!"
echo ""
echo "📝 Quick Test Commands:"
echo "======================="
echo ""
echo "# Test the connection (run on your local machine after setting up tunnel):"
echo "curl http://localhost:9090/health"
echo ""
echo "# Send a test message:"
echo 'curl -X POST http://localhost:9090/api/chat \'
echo '  -H "Content-Type: application/json" \'
echo '  -d "{\"message\": \"Hello from my local machine!\"}"'
echo ""
echo "🔐 Security Note:"
echo "=================="
echo "SSH tunneling is the most secure option as it encrypts all traffic."
echo "Never expose ports directly on cloud servers without proper authentication!"