#!/bin/bash

echo "=== Think AI Coding Examples ==="
echo ""
echo "Think AI currently has LIMITED CODING capabilities."
echo "It's primarily designed as a knowledge-based chatbot, not a code generator."
echo ""
echo "What Think AI CAN do:"
echo "1. Answer questions about programming concepts"
echo "2. Explain algorithms and data structures"
echo "3. Discuss software engineering principles"
echo ""
echo "What Think AI CANNOT reliably do:"
echo "1. Write actual code (it will often give explanations instead)"
echo "2. Debug complex programs"
echo "3. Generate complete applications"
echo ""
echo "To use Think AI for coding-related questions:"
echo ""
echo "1. Start the chat:"
echo "   ./target/release/think-ai chat"
echo ""
echo "2. Ask conceptual questions like:"
echo "   - 'What is a hash table?'"
echo "   - 'How does quicksort work?'"
echo "   - 'What is the difference between a stack and a queue?'"
echo ""
echo "For actual code generation, consider using:"
echo "- The JavaScript CLI: npx thinkai-quantum chat"
echo "- The Python CLI: think-ai chat (after pip install thinkai-quantum)"
echo "- Or integrate with a proper LLM like Claude or GPT"
echo ""
echo "=== Alternative: Use the coding assistant binary ==="
echo "There's also a dedicated coding binary you can try:"
echo "cargo build --release --bin think-ai-coding"
echo "./target/release/think-ai-coding"
echo ""