#!/bin/bash

echo "🎉 Think AI Coding CLI - Mode Switching Demo"
echo "============================================"
echo ""
echo "The coding CLI now has TWO modes:"
echo "  1. CODE mode - Generates code from your descriptions"
echo "  2. CHAT mode - Answers questions and has conversations"
echo ""
echo "To switch modes, simply type 'mode' in the CLI"
echo ""
echo "Let's test this with an interactive session..."
echo ""
echo "Running: ./target/release/think-ai-coding chat"
echo ""
echo "Try these commands in order:"
echo "  1. Type: hello"
echo "     (In CODE mode, generates hello world code)"
echo ""
echo "  2. Type: mode"
echo "     (Switches to CHAT mode)"
echo ""
echo "  3. Type: hello"
echo "     (In CHAT mode, greets you conversationally)"
echo ""
echo "  4. Type: what is the sun?"
echo "     (In CHAT mode, explains what the sun is)"
echo ""
echo "  5. Type: mode"
echo "     (Switches back to CODE mode)"
echo ""
echo "  6. Type: fibonacci"
echo "     (In CODE mode, generates fibonacci code)"
echo ""
echo "Starting interactive session..."
echo ""

exec ./target/release/think-ai-coding chat